version: '3.8'

services:
  pptp-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pptp-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ppp
    network_mode: "host"
    restart: always
    env_file:
      - .env
