services:
  openvpn-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openvpn-server
    network_mode: "host"
    privileged: true
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - ./app:/app
      - ./data/openvpn:/etc/openvpn
    env_file:
      - .env
